### ISSUE TITLE
Map is not working after upgrading to 2.0.1

### ISSUE THREAD

**Issue by cgtyysr** [NodeBB-Community/nodebb-plugin-osm-map#24]
Nodebb version: 2.5.7
Plugin version: 2.0.1

After upgrading my map is started to not working.
![image](https://user-images.githubusercontent.com/106465804/197634664-1ed60b35-46cb-4f94-9251-168a746d2052.png)

![image](https://user-images.githubusercontent.com/106465804/197634945-068074aa-abfa-4d1f-92ed-bd6c9342d340.png)

**Comment by julianlam** [comment]
Use v1.x.  v2.x of this plugin is for NodeBB v3 only.
